on:
  push:
    branches:
    - main

jobs:
  build-and-deploy-website:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.3.0
    - uses: actions/setup-node@v3.6.0
    - name: Install myst-cli
      run: npm install -g myst-cli
    - name: Build the book
      run: |
        cd myst
        myst build
    - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3.5.9
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./myst/_build/
